projects:
  blog:
    errbit:
      api_key: '36e7f2411ebd3b7ca97a8c04473f166e'
    semaphore:
      name: 'blog.subvisual.co'
  blog2:
    errbit:
      api_key: '36e7f2411ebd3b7ca97a8c04473f166e'
    semaphore:
      name: 'blog.subvisual.co'
  blog3:
    errbit:
      api_key: '36e7f2411ebd3b7ca97a8c04473f166e'
    semaphore:
      name: 'blog.subvisual.co'
  blog4:
    errbit:
      api_key: '36e7f2411ebd3b7ca97a8c04473f166e'
    semaphore:
      name: 'blog.subvisual.co'
  blog5:
    errbit:
      api_key: '36e7f2411ebd3b7ca97a8c04473f166e'
    semaphore:
      name: 'blog.subvisual.co'
