:errbit:
  :projects:
    :project_1:
      :api_key: '36e7f2411ebd3b7ca97a8c04473f166e'
    :project_2:
      :api_key: 'ccfad2a984e1986e2aaf4f325e77d462'
  :base_uri: 'https://log.subvisual.co'
  :date_format: '%d/%m %H:%M'
